version: '3.8'

services:

#######################################################################################################################
####################################################### AIRFLOW #######################################################
#######################################################################################################################

  postgres-airflow:
    image: postgres:15
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: ${AIRFLOW_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB}
    ports:
      - "${POSTGRES_AIRFLOW_PORT}:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    networks:
      - airflow_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_USER}", "-d", "${AIRFLOW_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-webserver:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-webserver
    depends_on:
      postgres-airflow:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres-airflow:5432/${AIRFLOW_DB}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=admin
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=admin
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || echo 'Airflow user already exists' &&
      airflow webserver"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - dbt_ssh_keys:/opt/airflow/dbt_ssh_keys
    user: root
    networks:
      - airflow_network
      - link_airflow_dbt_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 30s

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE}
    container_name: airflow-scheduler
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-webserver:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres-airflow:5432/${AIRFLOW_DB}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - dbt_ssh_keys:/opt/airflow/dbt_ssh_keys
    user: root
    networks:
      - airflow_network
      - link_airflow_dbt_network

  airflow-worker:
    image: ${AIRFLOW_IMAGE}
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-scheduler:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres-airflow:5432/${AIRFLOW_DB}
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
    command: airflow celery worker
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - dbt_ssh_keys:/opt/airflow/dbt_ssh_keys
    user: root
    networks:
      - airflow_network
      - link_airflow_dbt_network
    deploy:
      replicas: 3

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
    - redis_data:/data
    networks:
      - airflow_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      start_period: 5s

#######################################################################################################################
####################################################### DBT ###########################################################
#######################################################################################################################

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: dbt
    depends_on:
      postgres-dbt:
        condition: service_healthy
    environment:
      - DBT_PROFILES_DIR=/usr/app
      - POSTGRES_USER=${POSTGRES_DBT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DBT_PASSWORD}
      - DBLINK_HOST=postgres-dbt
      - DBLINK_DBNAME=${DATA_LAKE_DB}
      - DBLINK_USER=${POSTGRES_DBT_USER}
      - DBLINK_PASSWORD=${POSTGRES_DBT_PASSWORD}
    volumes:
      - ./dbt:/usr/app
      - dbt_ssh_keys:/root/.ssh
    working_dir: /usr/app
    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y openssh-server &&
        mkdir -p /root/.ssh &&
        if [ ! -f /root/.ssh/id_rsa ]; then
          ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N '';
        fi &&
        cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config &&
        echo 'AcceptEnv *' >> /etc/ssh/sshd_config &&
        service ssh start &&
        tail -f /dev/null
      "
    ports: 
      - "2222:22"
    networks:
      - dbt_network
      - link_airflow_dbt_network
  
  postgres-dbt:
    image: postgres:15
    container_name: postgres-dbt
    environment:
      POSTGRES_USER: ${POSTGRES_DBT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DBT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBT_DB}
    ports:
      - "${POSTGRES_DBT_PORT}:5432"
    volumes:
      - postgres_dbt_data:/var/lib/postgresql/data
      - ./postgres_config/init_postgres_dbt.sql:/docker-entrypoint-initdb.d/init_postgres_dbt.sql
    networks:
      - dbt_network
      - link_airflow_dbt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DBT_USER} -d ${POSTGRES_DBT_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s

  dbt-docs:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: dbt-docs
    depends_on:
      postgres-dbt:
        condition: service_healthy
      dbt:
        condition: service_started
    environment:
      - DBT_PROFILES_DIR=/usr/app
      - POSTGRES_USER=${POSTGRES_DBT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DBT_PASSWORD}
      - DBLINK_HOST=postgres-dbt
      - DBLINK_DBNAME=${DATA_LAKE_DB}
      - DBLINK_USER=${POSTGRES_DBT_USER}
      - DBLINK_PASSWORD=${POSTGRES_DBT_PASSWORD}
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    entrypoint: >
      bash -c "
        dbt deps &&
        dbt docs generate &&
        dbt docs serve --host 0.0.0.0 --port 8081
      "
    ports:
      - "${DBT_DOCS_PORT}:8081"
    networks:
      - dbt_network
      - link_airflow_dbt_network

#######################################################################################################################
####################################################### SPARK #########################################################
#######################################################################################################################

  jupyter-spark:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-spark
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=spark  # Fixed token for easy local access
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${SPARK_UI_PORT}:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    networks:
      - dbt_network # To access postgres-dbt
    user: root # To avoid permission issues with mounted volumes in some setups
    command: start-notebook.sh --NotebookApp.token='spark'

#######################################################################################################################
####################################################### PGADMIN ######################################################
#######################################################################################################################

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      postgres-dbt:
        condition: service_healthy
      postgres-airflow:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dbt_network
      - airflow_network
      - link_airflow_dbt_network

#######################################################################################################################
################################################ VOLUMES & NETWORKS ###################################################
#######################################################################################################################

volumes:
  postgres_airflow_data:
  postgres_dbt_data:
  redis_data:
  dbt_ssh_keys:
  pgadmin_data:

networks:
  airflow_network:
    driver: bridge
  dbt_network:
    driver: bridge
  link_airflow_dbt_network:
    driver: bridge